cloudWatch:
  enabled: true
  region: us-east-1
  logGroupName: /eks/app-logs
  logStreamPrefix: from-fluentbit-
  autoCreateGroup: true
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account_id>:role/fluentbit-role
