prometheusRule:
  rules:
    - alert: HighPodCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total[2m])) > 0.8
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected in pod"
